_target_: pytorch_lightning.Trainer

accelerator: "cpu" 
# accelerator: "gpu" 
# devices: 0 - Comment when using cpu and specify a number when using GPU

min_epochs: 100
max_epochs: 150

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
# resume_from_checkpoint: null

