_target_: {{cookiecutter.project_slug}}.models.detection_and_segmentation.DetectionAndSegmentation
lr: 0.0001
weight_decay: 0.0005

net:
  _target_: {{cookiecutter.project_slug}}.models.detection_and_segmentation.MaskRCNN
  num_classes: 2
  hidden_layer: 256